### ISSUE TITLE
v11 (again) for proto

### ISSUE THREAD

**Issue by lewispg228** [sparkfun/FT231X_Breakout#5]
1) Is there a correct version number in the copper? [YES]
comment: Yes, but would you please slide it to the board edge and thanks

2) Are measurements included for outer dimension and standoffs (Eagle layer 47)? [YES]
comment: Way to go remembering to update measures rock on

3) Please shift board so that the bottom left of the dimension is at 0,0. Thanks!

**Comment by SFE-KADE** [comment]
Right on. Should we add items 1 and 3 to the checklist officially?

**Comment by lewispg228** [comment]
thanks and will do (I'll run it by the committee tomorrow, but I'm confident it will be approved).
