### ISSUE TITLE
Checklist for v11 for Reds (again) - BOM/ prod id problem

### ISSUE THREAD

**Issue by lewispg228** [sparkfun/FT231X_Breakout#6]
Looks like R3, R4 and JP1 have different prod ids than what I'm seeing in sparkle. Could you please check this out, and make it all consistent. Thanks!

**Comment by SFE-KADE** [comment]
Fixed. Give it a second look.

**Comment by lewispg228** [comment]
Looks Good. And thanks for updating the library too!
